#!/bin/bash

function die () { echo "error: $1" >&2; exit 1; }

[ -d _deps ] || mkdir _deps || die 'failed to mkdir _deps'

while read name url; do
  echo "bootstrapping $name ..."

  if [ ! -e _deps/"$name" ]; then
    echo "$name" >> _deps/_update

    git clone "$url" _deps/"$name"
  else
    echo 'exists; skipping.'
  fi
done < _depsources

# --
