#!/bin/bash

what="$1"; shift

if [ "$what" == ALL ]; then
  ds=( $( ls _deps | grep -v '^_' | sed 's!^!_deps/!' ) )
elif [ "$what" == UPD ]; then
  ds=( $( cat _deps/_update | sed 's!^!_deps/!' ) )
else
  echo 'usage: git-deps { ALL | UPD } <git-cmd>' >&2
  exit 1
fi

mgit DS "${ds[@]}" END "$@"

# --
