#!/bin/bash

function die () { echo "error: $1" >&2; exit 1; }

if [ -n "$GIT_DEPS_DIRS" ]; then
  ds=( $GIT_DEPS_DIRS )
elif [ "$1" == ALL ]; then
  ds=( $( ls _deps | grep -v '^_' ) ) ; shift
elif [ "$1" == STDIN ]; then
  ds=() ; shift ; while read -r; do ds+=( "$REPLY" ); done
else
  ds=( $( cat _deps/_update ) )
fi

for name in "${ds[@]}"; do
  echo "==> $name <=="
  pushd _deps/"$name" > /dev/null || die "could not pushd _deps/$name"
    git "$@"
  popd > /dev/null
  echo
done

# --
