#!/bin/bash

function die () { echo "error: $1" >&2; exit 1; }

if [ -n "$GIT_DEPS_DIRS" ]; then
  ds=( $GIT_DEPS_DIRS )
else
  ds=( $( cat _deps/_update ) )
fi

for name in "${ds[@]}"; do
  echo "==> $name <=="
  pushd _deps/"$name" > /dev/null || die "could not pushd _deps/$name"
    git "$@"
  popd > /dev/null
  echo
done

# --
