#!/bin/bash

function die () { echo "error: $1" > &2; exit 1; }

if [ -n "$UPDATE_DEPS_DIRS" ]; then
  ds=( $UPDATE_DEPS_DIRS )
else
  ds=( $( cat _deps/_update ) )
fi

for name in "${ds[@]}"; do
  echo "updating $name ..."
  pushd _deps/"$name" > /dev/null || die "could not pushd _deps/$name"
    git pull
  popd > /dev/null
  echo 'done.'
done

# --
